// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;

namespace QuickJS;

/// <summary>
/// Bytecode interpreter for executing JavaScript functions.
/// </summary>
/// <remarks>
/// <para>
/// The interpreter executes bytecode generated by the parser/compiler.
/// It uses a stack-based virtual machine model where:
/// </para>
/// <list type="bullet">
/// <item>Values are pushed onto and popped from an operand stack</item>
/// <item>A program counter (PC) tracks the current instruction</item>
/// <item>Opcodes consume operands from the stack and push results</item>
/// </list>
/// <para>
/// Based on JS_CallInternal from QuickJS (quickjs.c lines 17356-20000+).
/// </para>
/// </remarks>
public sealed class Interpreter
{
    #region Fields

    private readonly JSContext _context;
    private readonly JSValue[] _stack;
    private int _stackPointer;
    private readonly int _maxStackSize;

    /// <summary>
    /// The current call frame containing locals, args, and var refs.
    /// </summary>
    private CallFrame? _currentFrame;

    #endregion

    #region Constructor

    /// <summary>
    /// Initializes a new instance of the <see cref="Interpreter"/> class.
    /// </summary>
    /// <param name="context">The JavaScript execution context.</param>
    /// <param name="stackSize">The maximum operand stack size.</param>
    public Interpreter(JSContext context, int stackSize = 512)
    {
        _context = context ?? throw new ArgumentNullException(nameof(context));
        _maxStackSize = stackSize;
        _stack = new JSValue[stackSize];
        _stackPointer = 0;
    }

    #endregion

    #region Properties

    /// <summary>
    /// Gets the execution context.
    /// </summary>
    public JSContext Context => _context;

    /// <summary>
    /// Gets the current stack pointer (number of values on the stack).
    /// </summary>
    public int StackPointer => _stackPointer;

    /// <summary>
    /// Gets the maximum stack size.
    /// </summary>
    public int MaxStackSize => _maxStackSize;

    /// <summary>
    /// Gets the available stack space.
    /// </summary>
    public int AvailableStackSpace => _maxStackSize - _stackPointer;

    /// <summary>
    /// Gets whether the stack is empty.
    /// </summary>
    public bool IsStackEmpty => _stackPointer == 0;

    /// <summary>
    /// Gets whether an exception has been thrown.
    /// </summary>
    public bool HasException => _context.HasException;

    /// <summary>
    /// Gets or sets the current call frame.
    /// </summary>
    public CallFrame? CurrentFrame
    {
        get => _currentFrame;
        set => _currentFrame = value;
    }

    #endregion

    #region Call Helpers

    private JSValue CallFunction(JSValue calleeVal, JSValue thisVal, JSValue[] args, bool isConstructor = false)
    {
        if (!calleeVal.IsObject)
        {
            _context.ThrowTypeError("Not a function");
            return JSValue.Exception;
        }

        var calleeObj = calleeVal.AsObject();
        if (calleeObj is JSFunction func)
        {
            // Native functions
            if (func.NativeFunction != null || func.NativeFunctionMagic != null)
            {
                try
                {
                    var result = func.CallNative(thisVal, args);
                    if (isConstructor && !result.IsObject)
                        return thisVal;
                    return result;
                }
                catch (JSException ex)
                {
                    _context.ThrowError(JSErrorType.Error, ex.Message);
                    return JSValue.Exception;
                }
            }

            // Bytecode functions
            var fd = func.FunctionDef;
            if (fd == null)
            {
                _context.ThrowTypeError("Not a callable function");
                return JSValue.Exception;
            }

            var savedFrame = _currentFrame;
            try
            {
                var frame = new CallFrame(fd, thisVal, args, func.VarRefs, savedFrame);
                _currentFrame = frame;
                var result = Execute(fd);
                if (isConstructor && !result.IsObject)
                    return thisVal;
                return result;
            }
            finally
            {
                _currentFrame = savedFrame;
            }
        }

        _context.ThrowTypeError("Not a function");
        return JSValue.Exception;
    }

    #endregion

    #region Stack Operations

    /// <summary>
    /// Pushes a value onto the operand stack.
    /// </summary>
    /// <param name="value">The value to push.</param>
    /// <exception cref="JSException">Thrown when the stack overflows.</exception>
    public void Push(JSValue value)
    {
        if (_stackPointer >= _maxStackSize)
        {
            ThrowStackOverflow();
            return;
        }
        _stack[_stackPointer++] = value;
    }

    /// <summary>
    /// Pops a value from the operand stack.
    /// </summary>
    /// <returns>The popped value.</returns>
    /// <exception cref="JSException">Thrown when the stack is empty.</exception>
    public JSValue Pop()
    {
        if (_stackPointer <= 0)
        {
            ThrowStackUnderflow();
            return JSValue.Undefined;
        }
        return _stack[--_stackPointer];
    }

    /// <summary>
    /// Peeks at the top value on the stack without removing it.
    /// </summary>
    /// <returns>The top value.</returns>
    /// <exception cref="JSException">Thrown when the stack is empty.</exception>
    public JSValue Peek()
    {
        if (_stackPointer <= 0)
        {
            ThrowStackUnderflow();
            return JSValue.Undefined;
        }
        return _stack[_stackPointer - 1];
    }

    /// <summary>
    /// Peeks at a value at the specified depth from the top.
    /// </summary>
    /// <param name="depth">The depth from the top (0 = top, 1 = second from top, etc.).</param>
    /// <returns>The value at the specified depth.</returns>
    public JSValue PeekAt(int depth)
    {
        int index = _stackPointer - 1 - depth;
        if (index < 0 || index >= _stackPointer)
        {
            ThrowStackUnderflow();
            return JSValue.Undefined;
        }
        return _stack[index];
    }

    /// <summary>
    /// Drops the top value from the stack (OP_drop).
    /// </summary>
    public void Drop()
    {
        if (_stackPointer > 0)
        {
            _stackPointer--;
        }
    }

    /// <summary>
    /// Duplicates the top value (OP_dup): a -> a a
    /// </summary>
    public void Dup()
    {
        if (_stackPointer <= 0)
        {
            ThrowStackUnderflow();
            return;
        }
        if (_stackPointer >= _maxStackSize)
        {
            ThrowStackOverflow();
            return;
        }
        _stack[_stackPointer] = _stack[_stackPointer - 1];
        _stackPointer++;
    }

    /// <summary>
    /// Duplicates the top two values (OP_dup2): a b -> a b a b
    /// </summary>
    public void Dup2()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }
        if (_stackPointer + 2 > _maxStackSize)
        {
            ThrowStackOverflow();
            return;
        }
        _stack[_stackPointer] = _stack[_stackPointer - 2];
        _stack[_stackPointer + 1] = _stack[_stackPointer - 1];
        _stackPointer += 2;
    }

    /// <summary>
    /// Duplicates the top three values (OP_dup3): a b c -> a b c a b c
    /// </summary>
    public void Dup3()
    {
        if (_stackPointer < 3)
        {
            ThrowStackUnderflow();
            return;
        }
        if (_stackPointer + 3 > _maxStackSize)
        {
            ThrowStackOverflow();
            return;
        }
        _stack[_stackPointer] = _stack[_stackPointer - 3];
        _stack[_stackPointer + 1] = _stack[_stackPointer - 2];
        _stack[_stackPointer + 2] = _stack[_stackPointer - 1];
        _stackPointer += 3;
    }

    /// <summary>
    /// Duplicates the second value (OP_dup1): a b -> a a b
    /// </summary>
    public void Dup1()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }
        if (_stackPointer >= _maxStackSize)
        {
            ThrowStackOverflow();
            return;
        }
        _stack[_stackPointer] = _stack[_stackPointer - 1];
        _stack[_stackPointer - 1] = _stack[_stackPointer - 2];
        _stackPointer++;
    }

    /// <summary>
    /// Removes the second item (OP_nip): a b -> b
    /// </summary>
    public void Nip()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }
        _stack[_stackPointer - 2] = _stack[_stackPointer - 1];
        _stackPointer--;
    }

    /// <summary>
    /// Removes the third item (OP_nip1): a b c -> b c
    /// </summary>
    public void Nip1()
    {
        if (_stackPointer < 3)
        {
            ThrowStackUnderflow();
            return;
        }
        _stack[_stackPointer - 3] = _stack[_stackPointer - 2];
        _stack[_stackPointer - 2] = _stack[_stackPointer - 1];
        _stackPointer--;
    }

    /// <summary>
    /// Swaps the top two values (OP_swap): a b -> b a
    /// </summary>
    public void Swap()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }
        var temp = _stack[_stackPointer - 1];
        _stack[_stackPointer - 1] = _stack[_stackPointer - 2];
        _stack[_stackPointer - 2] = temp;
    }

    /// <summary>
    /// Rotates top three values left (OP_rot3l): x a b -> a b x (231)
    /// </summary>
    public void Rot3L()
    {
        if (_stackPointer < 3)
        {
            ThrowStackUnderflow();
            return;
        }
        var tmp = _stack[_stackPointer - 3];
        _stack[_stackPointer - 3] = _stack[_stackPointer - 2];
        _stack[_stackPointer - 2] = _stack[_stackPointer - 1];
        _stack[_stackPointer - 1] = tmp;
    }

    /// <summary>
    /// Rotates top three values right (OP_rot3r): a b x -> x a b (312)
    /// </summary>
    public void Rot3R()
    {
        if (_stackPointer < 3)
        {
            ThrowStackUnderflow();
            return;
        }
        var tmp = _stack[_stackPointer - 1];
        _stack[_stackPointer - 1] = _stack[_stackPointer - 2];
        _stack[_stackPointer - 2] = _stack[_stackPointer - 3];
        _stack[_stackPointer - 3] = tmp;
    }

    /// <summary>
    /// Permutes top three (OP_perm3): obj a b -> a obj b (213)
    /// </summary>
    public void Perm3()
    {
        if (_stackPointer < 3)
        {
            ThrowStackUnderflow();
            return;
        }
        var tmp = _stack[_stackPointer - 2];
        _stack[_stackPointer - 2] = _stack[_stackPointer - 3];
        _stack[_stackPointer - 3] = tmp;
    }

    /// <summary>
    /// Insert duplicate at second position (OP_insert2): obj a -> a obj a
    /// </summary>
    public void Insert2()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }
        if (_stackPointer >= _maxStackSize)
        {
            ThrowStackOverflow();
            return;
        }
        _stack[_stackPointer] = _stack[_stackPointer - 1];
        _stack[_stackPointer - 1] = _stack[_stackPointer - 2];
        _stack[_stackPointer - 2] = _stack[_stackPointer];
        _stackPointer++;
    }

    /// <summary>
    /// Insert duplicate at third position (OP_insert3): obj prop a -> a obj prop a
    /// </summary>
    public void Insert3()
    {
        if (_stackPointer < 3)
        {
            ThrowStackUnderflow();
            return;
        }
        if (_stackPointer >= _maxStackSize)
        {
            ThrowStackOverflow();
            return;
        }
        _stack[_stackPointer] = _stack[_stackPointer - 1];
        _stack[_stackPointer - 1] = _stack[_stackPointer - 2];
        _stack[_stackPointer - 2] = _stack[_stackPointer - 3];
        _stack[_stackPointer - 3] = _stack[_stackPointer];
        _stackPointer++;
    }

    /// <summary>
    /// Clears the entire stack.
    /// </summary>
    public void ClearStack()
    {
        _stackPointer = 0;
    }

    /// <summary>
    /// Gets a copy of the current stack contents for debugging.
    /// </summary>
    /// <returns>An array of the current stack values.</returns>
    public JSValue[] GetStackSnapshot()
    {
        var snapshot = new JSValue[_stackPointer];
        Array.Copy(_stack, 0, snapshot, 0, _stackPointer);
        return snapshot;
    }

    #endregion

    #region Arithmetic Operations

    /// <summary>
    /// Addition: pops two values, pushes their sum.
    /// Handles int + int, float + float, and string concatenation.
    /// </summary>
    public void Add()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both integers
        if (op1.IsInt && op2.IsInt)
        {
            long result = (long)op1.ToInt32() + op2.ToInt32();
            if (result >= int.MinValue && result <= int.MaxValue)
            {
                _stack[_stackPointer - 1] = JSValue.FromInt32((int)result);
            }
            else
            {
                // Overflow to double
                _stack[_stackPointer - 1] = JSValue.FromDouble(result);
            }
            return;
        }

        // Fast path: both doubles
        if (op1.IsNumber && op2.IsNumber)
        {
            _stack[_stackPointer - 1] = JSValue.FromDouble(op1.ToDouble() + op2.ToDouble());
            return;
        }

        // String concatenation
        if (op1.IsString || op2.IsString)
        {
            string s1 = JSValueConversion.ToString(op1);
            string s2 = JSValueConversion.ToString(op2);
            _stack[_stackPointer - 1] = JSValue.FromString(s1 + s2);
            return;
        }

        // General case: convert to primitives
        AddSlow(op1, op2);
    }

    private void AddSlow(JSValue op1, JSValue op2)
    {
        // ToPrimitive hint: default (number for most, string for Date)
        var prim1 = ToPrimitive(op1);
        var prim2 = ToPrimitive(op2);

        if (prim1.IsString || prim2.IsString)
        {
            string s1 = JSValueConversion.ToString(prim1);
            string s2 = JSValueConversion.ToString(prim2);
            _stack[_stackPointer - 1] = JSValue.FromString(s1 + s2);
        }
        else
        {
            double d1 = JSValueConversion.ToNumber(prim1);
            double d2 = JSValueConversion.ToNumber(prim2);
            _stack[_stackPointer - 1] = JSValue.FromDouble(d1 + d2);
        }
    }

    /// <summary>
    /// Subtraction: pops two values, pushes their difference.
    /// </summary>
    public void Sub()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both integers
        if (op1.IsInt && op2.IsInt)
        {
            long result = (long)op1.ToInt32() - op2.ToInt32();
            if (result >= int.MinValue && result <= int.MaxValue)
            {
                _stack[_stackPointer - 1] = JSValue.FromInt32((int)result);
            }
            else
            {
                _stack[_stackPointer - 1] = JSValue.FromDouble(result);
            }
            return;
        }

        // General case
        double d1 = JSValueConversion.ToNumber(op1);
        double d2 = JSValueConversion.ToNumber(op2);
        _stack[_stackPointer - 1] = JSValue.FromDouble(d1 - d2);
    }

    /// <summary>
    /// Multiplication: pops two values, pushes their product.
    /// </summary>
    public void Mul()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both integers
        if (op1.IsInt && op2.IsInt)
        {
            int v1 = op1.ToInt32();
            int v2 = op2.ToInt32();
            long result = (long)v1 * v2;

            if (result >= int.MinValue && result <= int.MaxValue && !(result == 0 && (v1 | v2) < 0))
            {
                _stack[_stackPointer - 1] = JSValue.FromInt32((int)result);
            }
            else
            {
                // Handle -0 and overflow
                _stack[_stackPointer - 1] = JSValue.FromDouble((double)result);
            }
            return;
        }

        // General case
        double d1 = JSValueConversion.ToNumber(op1);
        double d2 = JSValueConversion.ToNumber(op2);
        _stack[_stackPointer - 1] = JSValue.FromDouble(d1 * d2);
    }

    /// <summary>
    /// Division: pops two values, pushes their quotient.
    /// Always returns a double (JavaScript division is always floating-point).
    /// </summary>
    public void Div()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        double d1 = JSValueConversion.ToNumber(op1);
        double d2 = JSValueConversion.ToNumber(op2);
        _stack[_stackPointer - 1] = JSValue.FromDouble(d1 / d2);
    }

    /// <summary>
    /// Modulo: pops two values, pushes the remainder.
    /// </summary>
    public void Mod()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both positive integers
        if (op1.IsInt && op2.IsInt)
        {
            int v1 = op1.ToInt32();
            int v2 = op2.ToInt32();
            if (v1 >= 0 && v2 > 0)
            {
                _stack[_stackPointer - 1] = JSValue.FromInt32(v1 % v2);
                return;
            }
        }

        // General case: use IEEE 754 remainder
        double d1 = JSValueConversion.ToNumber(op1);
        double d2 = JSValueConversion.ToNumber(op2);
        _stack[_stackPointer - 1] = JSValue.FromDouble(d1 % d2);
    }

    /// <summary>
    /// Power: pops two values, pushes base ** exponent.
    /// </summary>
    public void Pow()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        double d1 = JSValueConversion.ToNumber(op1);
        double d2 = JSValueConversion.ToNumber(op2);
        _stack[_stackPointer - 1] = JSValue.FromDouble(Math.Pow(d1, d2));
    }

    /// <summary>
    /// Unary plus: converts top value to number.
    /// </summary>
    public void Plus()
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var op = _stack[_stackPointer - 1];
        if (op.IsNumber)
            return;

        double d = JSValueConversion.ToNumber(op);
        _stack[_stackPointer - 1] = JSValue.FromDouble(d);
    }

    /// <summary>
    /// Unary negation: negates top value.
    /// </summary>
    public void Neg()
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var op = _stack[_stackPointer - 1];

        if (op.IsInt)
        {
            int val = op.ToInt32();
            if (val == 0)
            {
                // -0 must be a double
                _stack[_stackPointer - 1] = JSValue.FromDouble(-0.0);
            }
            else if (val == int.MinValue)
            {
                // Overflow
                _stack[_stackPointer - 1] = JSValue.FromDouble(-(double)val);
            }
            else
            {
                _stack[_stackPointer - 1] = JSValue.FromInt32(-val);
            }
            return;
        }

        double d = JSValueConversion.ToNumber(op);
        _stack[_stackPointer - 1] = JSValue.FromDouble(-d);
    }

    /// <summary>
    /// Increment: adds 1 to top value.
    /// </summary>
    public void Inc()
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var op = _stack[_stackPointer - 1];

        if (op.IsInt)
        {
            int val = op.ToInt32();
            if (val < int.MaxValue)
            {
                _stack[_stackPointer - 1] = JSValue.FromInt32(val + 1);
                return;
            }
        }

        double d = JSValueConversion.ToNumber(op);
        _stack[_stackPointer - 1] = JSValue.FromDouble(d + 1);
    }

    /// <summary>
    /// Decrement: subtracts 1 from top value.
    /// </summary>
    public void Dec()
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var op = _stack[_stackPointer - 1];

        if (op.IsInt)
        {
            int val = op.ToInt32();
            if (val > int.MinValue)
            {
                _stack[_stackPointer - 1] = JSValue.FromInt32(val - 1);
                return;
            }
        }

        double d = JSValueConversion.ToNumber(op);
        _stack[_stackPointer - 1] = JSValue.FromDouble(d - 1);
    }

    #endregion

    #region Bitwise Operations

    /// <summary>
    /// Bitwise NOT: ~a
    /// </summary>
    public void Not()
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var op = _stack[_stackPointer - 1];
        int val = JSValueConversion.ToInt32(op);
        _stack[_stackPointer - 1] = JSValue.FromInt32(~val);
    }

    /// <summary>
    /// Bitwise AND: a &amp; b
    /// </summary>
    public void And()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        int v1 = JSValueConversion.ToInt32(op1);
        int v2 = JSValueConversion.ToInt32(op2);
        _stack[_stackPointer - 1] = JSValue.FromInt32(v1 & v2);
    }

    /// <summary>
    /// Bitwise OR: a | b
    /// </summary>
    public void Or()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        int v1 = JSValueConversion.ToInt32(op1);
        int v2 = JSValueConversion.ToInt32(op2);
        _stack[_stackPointer - 1] = JSValue.FromInt32(v1 | v2);
    }

    /// <summary>
    /// Bitwise XOR: a ^ b
    /// </summary>
    public void Xor()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        int v1 = JSValueConversion.ToInt32(op1);
        int v2 = JSValueConversion.ToInt32(op2);
        _stack[_stackPointer - 1] = JSValue.FromInt32(v1 ^ v2);
    }

    /// <summary>
    /// Left shift: a &lt;&lt; b
    /// </summary>
    public void Shl()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        int v1 = JSValueConversion.ToInt32(op1);
        uint v2 = JSValueConversion.ToUInt32(op2);
        int shift = (int)(v2 & 0x1F); // Only use bottom 5 bits
        _stack[_stackPointer - 1] = JSValue.FromInt32(v1 << shift);
    }

    /// <summary>
    /// Signed right shift: a >> b
    /// </summary>
    public void Sar()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        int v1 = JSValueConversion.ToInt32(op1);
        uint v2 = JSValueConversion.ToUInt32(op2);
        int shift = (int)(v2 & 0x1F);
        _stack[_stackPointer - 1] = JSValue.FromInt32(v1 >> shift);
    }

    /// <summary>
    /// Unsigned right shift: a >>> b
    /// </summary>
    public void Shr()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        uint v1 = JSValueConversion.ToUInt32(op1);
        uint v2 = JSValueConversion.ToUInt32(op2);
        int shift = (int)(v2 & 0x1F);
        uint result = v1 >> shift;
        // Result is uint, but fits in int32 range after shift, or we return as double
        if (result <= int.MaxValue)
        {
            _stack[_stackPointer - 1] = JSValue.FromInt32((int)result);
        }
        else
        {
            _stack[_stackPointer - 1] = JSValue.FromDouble(result);
        }
    }

    #endregion

    #region Comparison Operations

    /// <summary>
    /// Less than comparison: a &lt; b
    /// </summary>
    public void Lt()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both integers
        if (op1.IsInt && op2.IsInt)
        {
            _stack[_stackPointer - 1] = JSValue.FromBoolean(op1.ToInt32() < op2.ToInt32());
            return;
        }

        var result = AbstractRelationalComparison(op1, op2, true);
        _stack[_stackPointer - 1] = result ?? JSValue.False;
    }

    /// <summary>
    /// Less than or equal comparison: a &lt;= b
    /// </summary>
    public void Lte()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both integers
        if (op1.IsInt && op2.IsInt)
        {
            _stack[_stackPointer - 1] = JSValue.FromBoolean(op1.ToInt32() <= op2.ToInt32());
            return;
        }

        // a <= b is !(b < a)
        var result = AbstractRelationalComparison(op2, op1, false);
        if (result == null)
        {
            _stack[_stackPointer - 1] = JSValue.False;
        }
        else
        {
            _stack[_stackPointer - 1] = JSValue.FromBoolean(!result.Value.IsTrue);
        }
    }

    /// <summary>
    /// Greater than comparison: a > b
    /// </summary>
    public void Gt()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both integers
        if (op1.IsInt && op2.IsInt)
        {
            _stack[_stackPointer - 1] = JSValue.FromBoolean(op1.ToInt32() > op2.ToInt32());
            return;
        }

        // a > b is b < a
        var result = AbstractRelationalComparison(op2, op1, false);
        _stack[_stackPointer - 1] = result ?? JSValue.False;
    }

    /// <summary>
    /// Greater than or equal comparison: a >= b
    /// </summary>
    public void Gte()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        // Fast path: both integers
        if (op1.IsInt && op2.IsInt)
        {
            _stack[_stackPointer - 1] = JSValue.FromBoolean(op1.ToInt32() >= op2.ToInt32());
            return;
        }

        // a >= b is !(a < b)
        var result = AbstractRelationalComparison(op1, op2, true);
        if (result == null)
        {
            _stack[_stackPointer - 1] = JSValue.False;
        }
        else
        {
            _stack[_stackPointer - 1] = JSValue.FromBoolean(!result.Value.IsTrue);
        }
    }

    /// <summary>
    /// Abstract relational comparison as per ECMAScript spec.
    /// Returns null for undefined result (NaN comparisons).
    /// </summary>
    private JSValue? AbstractRelationalComparison(JSValue x, JSValue y, bool leftFirst)
    {
        JSValue px, py;

        if (leftFirst)
        {
            px = ToPrimitive(x, "number");
            py = ToPrimitive(y, "number");
        }
        else
        {
            py = ToPrimitive(y, "number");
            px = ToPrimitive(x, "number");
        }

        // String comparison
        if (px.IsString && py.IsString)
        {
            string sx = px.ToString()!;
            string sy = py.ToString()!;
            return JSValue.FromBoolean(string.Compare(sx, sy, StringComparison.Ordinal) < 0);
        }

        // Numeric comparison
        double nx = JSValueConversion.ToNumber(px);
        double ny = JSValueConversion.ToNumber(py);

        if (double.IsNaN(nx) || double.IsNaN(ny))
            return null;

        return JSValue.FromBoolean(nx < ny);
    }

    /// <summary>
    /// Abstract equality comparison: a == b
    /// </summary>
    public void Eq()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        _stack[_stackPointer - 1] = JSValue.FromBoolean(AbstractEqualityComparison(op1, op2));
    }

    /// <summary>
    /// Abstract inequality comparison: a != b
    /// </summary>
    public void Neq()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        _stack[_stackPointer - 1] = JSValue.FromBoolean(!AbstractEqualityComparison(op1, op2));
    }

    /// <summary>
    /// Strict equality comparison: a === b
    /// </summary>
    public void StrictEq()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        _stack[_stackPointer - 1] = JSValue.FromBoolean(StrictEqualityComparison(op1, op2));
    }

    /// <summary>
    /// Strict inequality comparison: a !== b
    /// </summary>
    public void StrictNeq()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var op2 = _stack[_stackPointer - 1];
        var op1 = _stack[_stackPointer - 2];
        _stackPointer--;

        _stack[_stackPointer - 1] = JSValue.FromBoolean(!StrictEqualityComparison(op1, op2));
    }

    /// <summary>
    /// Abstract equality comparison as per ECMAScript spec (==).
    /// </summary>
    private bool AbstractEqualityComparison(JSValue x, JSValue y)
    {
        // Same type - use strict comparison
        if (x.Tag == y.Tag)
        {
            return StrictEqualityComparison(x, y);
        }

        // null == undefined
        if ((x.IsNull && y.IsUndefined) || (x.IsUndefined && y.IsNull))
        {
            return true;
        }

        // Number == String -> compare as numbers
        if (x.IsNumber && y.IsString)
        {
            return x.ToDouble() == JSValueConversion.ToNumber(y);
        }
        if (x.IsString && y.IsNumber)
        {
            return JSValueConversion.ToNumber(x) == y.ToDouble();
        }

        // Boolean -> Number
        if (x.IsBool)
        {
            return AbstractEqualityComparison(JSValue.FromDouble(x.IsTrue ? 1 : 0), y);
        }
        if (y.IsBool)
        {
            return AbstractEqualityComparison(x, JSValue.FromDouble(y.IsTrue ? 1 : 0));
        }

        // Object == primitive -> compare ToPrimitive(object) with primitive
        if ((x.IsString || x.IsNumber) && y.IsObject)
        {
            return AbstractEqualityComparison(x, ToPrimitive(y));
        }
        if (x.IsObject && (y.IsString || y.IsNumber))
        {
            return AbstractEqualityComparison(ToPrimitive(x), y);
        }

        return false;
    }

    /// <summary>
    /// Strict equality comparison as per ECMAScript spec (===).
    /// </summary>
    private bool StrictEqualityComparison(JSValue x, JSValue y)
    {
        // Different types are never strictly equal
        if (x.Tag != y.Tag)
        {
            // Handle int32 vs float64 special case
            if (x.IsNumber && y.IsNumber)
            {
                return x.ToDouble() == y.ToDouble();
            }
            return false;
        }

        // Undefined === Undefined
        if (x.IsUndefined)
            return true;

        // Null === Null
        if (x.IsNull)
            return true;

        // Number comparison
        if (x.IsNumber)
        {
            double dx = x.ToDouble();
            double dy = y.ToDouble();
            // NaN is not equal to itself
            if (double.IsNaN(dx) || double.IsNaN(dy))
                return false;
            return dx == dy;
        }

        // String comparison
        if (x.IsString)
        {
            return x.ToString() == y.ToString();
        }

        // Boolean comparison
        if (x.IsBool)
        {
            return x.IsTrue == y.IsTrue;
        }

        // Object comparison - reference equality
        if (x.IsObject)
        {
            return ReferenceEquals(x.AsObject(), y.AsObject());
        }

        return false;
    }

    #endregion

    #region Logical Operations

    /// <summary>
    /// Logical NOT: !a
    /// </summary>
    public void LogicalNot()
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var op = _stack[_stackPointer - 1];
        bool truthy = JSValueConversion.ToBoolean(op);
        _stack[_stackPointer - 1] = JSValue.FromBoolean(!truthy);
    }

    /// <summary>
    /// Checks if value is undefined or null.
    /// </summary>
    public void IsUndefinedOrNull()
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var op = _stack[_stackPointer - 1];
        _stack[_stackPointer - 1] = JSValue.FromBoolean(op.IsUndefined || op.IsNull);
    }

    #endregion

    #region Variable Access Operations

    /// <summary>
    /// Gets a local variable by index: -> value
    /// </summary>
    /// <param name="index">The local variable index.</param>
    public void GetLoc(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        Push(_currentFrame.GetLocal(index));
    }

    /// <summary>
    /// Puts (assigns) a local variable by index: value ->
    /// </summary>
    /// <param name="index">The local variable index.</param>
    public void PutLoc(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Pop();
        _currentFrame.SetLocal(index, value);
    }

    /// <summary>
    /// Sets a local variable, keeping value on stack: value -> value
    /// </summary>
    /// <param name="index">The local variable index.</param>
    public void SetLoc(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Peek();
        _currentFrame.SetLocal(index, value);
    }

    /// <summary>
    /// Gets an argument by index: -> value
    /// </summary>
    /// <param name="index">The argument index.</param>
    public void GetArg(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        Push(_currentFrame.GetArg(index));
    }

    /// <summary>
    /// Puts (assigns) an argument by index: value ->
    /// </summary>
    /// <param name="index">The argument index.</param>
    public void PutArg(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Pop();
        _currentFrame.SetArg(index, value);
    }

    /// <summary>
    /// Sets an argument, keeping value on stack: value -> value
    /// </summary>
    /// <param name="index">The argument index.</param>
    public void SetArg(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Peek();
        _currentFrame.SetArg(index, value);
    }

    /// <summary>
    /// Gets a closure variable by index: -> value
    /// </summary>
    /// <param name="index">The var ref index.</param>
    public void GetVarRef(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        Push(_currentFrame.GetVarRefValue(index));
    }

    /// <summary>
    /// Puts (assigns) a closure variable by index: value ->
    /// </summary>
    /// <param name="index">The var ref index.</param>
    public void PutVarRef(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Pop();
        var varRef = _currentFrame.GetVarRef(index);
        if (varRef != null)
        {
            if (varRef.IsConst)
            {
                _context.ThrowTypeError("Assignment to constant variable");
                return;
            }
            varRef.Value = value;
        }
    }

    /// <summary>
    /// Sets a closure variable, keeping value on stack: value -> value
    /// </summary>
    /// <param name="index">The var ref index.</param>
    public void SetVarRef(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Peek();
        var varRef = _currentFrame.GetVarRef(index);
        if (varRef != null)
        {
            if (varRef.IsConst)
            {
                _context.ThrowTypeError("Assignment to constant variable");
                return;
            }
            varRef.Value = value;
        }
    }

    /// <summary>
    /// Gets a closure variable with TDZ check: -> value
    /// </summary>
    /// <param name="index">The var ref index.</param>
    public void GetVarRefCheck(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var varRef = _currentFrame.GetVarRef(index);
        if (varRef == null)
        {
            Push(JSValue.Undefined);
            return;
        }
        var value = varRef.Value;
        if (value.IsUninitialized)
        {
            _context.ThrowReferenceError("Cannot access variable before initialization");
            return;
        }
        Push(value);
    }

    /// <summary>
    /// Puts a closure variable with TDZ check: value ->
    /// </summary>
    /// <param name="index">The var ref index.</param>
    public void PutVarRefCheck(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Pop();
        var varRef = _currentFrame.GetVarRef(index);
        if (varRef == null)
        {
            return;
        }
        if (varRef.Value.IsUninitialized)
        {
            _context.ThrowReferenceError("Cannot access variable before initialization");
            return;
        }
        if (varRef.IsConst)
        {
            _context.ThrowTypeError("Assignment to constant variable");
            return;
        }
        varRef.Value = value;
    }

    /// <summary>
    /// Gets a local variable with TDZ check: -> value
    /// </summary>
    /// <param name="index">The local variable index.</param>
    public void GetLocCheck(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = _currentFrame.GetLocal(index);
        if (value.IsUninitialized)
        {
            _context.ThrowReferenceError("Cannot access variable before initialization");
            return;
        }
        Push(value);
    }

    /// <summary>
    /// Puts a local variable with TDZ check: value ->
    /// </summary>
    /// <param name="index">The local variable index.</param>
    public void PutLocCheck(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var currentValue = _currentFrame.GetLocal(index);
        if (currentValue.IsUninitialized)
        {
            _context.ThrowReferenceError("Cannot access variable before initialization");
            return;
        }
        var value = Pop();
        _currentFrame.SetLocal(index, value);
    }

    /// <summary>
    /// Initializes a local variable (for let/const): value ->
    /// </summary>
    /// <param name="index">The local variable index.</param>
    public void PutLocCheckInit(int index)
    {
        if (_currentFrame == null)
        {
            _context.ThrowReferenceError("No active call frame");
            return;
        }
        var value = Pop();
        _currentFrame.SetLocal(index, value);
    }

    /// <summary>
    /// Marks a local variable as uninitialized (for TDZ).
    /// </summary>
    /// <param name="index">The local variable index.</param>
    public void SetLocUninitialized(int index)
    {
        if (_currentFrame == null)
        {
            return;
        }
        _currentFrame.SetLocal(index, JSValue.Uninitialized);
    }

    #endregion

    #region Property Access Operations

    /// <summary>
    /// Gets a property by name: obj -> value
    /// </summary>
    /// <param name="propertyName">The property name.</param>
    public void GetField(string propertyName)
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var obj = _stack[_stackPointer - 1];

        // Get property from object
        var value = GetPropertyValue(obj, propertyName);
        _stack[_stackPointer - 1] = value;
    }

    /// <summary>
    /// Gets a property by name, keeping object: obj -> obj value
    /// </summary>
    /// <param name="propertyName">The property name.</param>
    public void GetField2(string propertyName)
    {
        if (_stackPointer < 1)
        {
            ThrowStackUnderflow();
            return;
        }

        var obj = _stack[_stackPointer - 1];

        // Get property from object
        var value = GetPropertyValue(obj, propertyName);
        Push(value);
    }

    /// <summary>
    /// Sets a property by name: obj value ->
    /// </summary>
    /// <param name="propertyName">The property name.</param>
    public void PutField(string propertyName)
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var value = _stack[_stackPointer - 1];
        var obj = _stack[_stackPointer - 2];
        _stackPointer -= 2;

        SetPropertyValue(obj, propertyName, value);
    }

    /// <summary>
    /// Gets an array element by index: obj index -> value
    /// </summary>
    public void GetArrayEl()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var index = _stack[_stackPointer - 1];
        var obj = _stack[_stackPointer - 2];
        _stackPointer--;

        var value = GetElementValue(obj, index);
        _stack[_stackPointer - 1] = value;
    }

    /// <summary>
    /// Gets an array element, keeping object: obj index -> obj value
    /// </summary>
    public void GetArrayEl2()
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var index = _stack[_stackPointer - 1];
        var obj = _stack[_stackPointer - 2];

        var value = GetElementValue(obj, index);
        _stack[_stackPointer - 1] = value;
    }

    /// <summary>
    /// Sets an array element: obj index value ->
    /// </summary>
    public void PutArrayEl()
    {
        if (_stackPointer < 3)
        {
            ThrowStackUnderflow();
            return;
        }

        var value = _stack[_stackPointer - 1];
        var index = _stack[_stackPointer - 2];
        var obj = _stack[_stackPointer - 3];
        _stackPointer -= 3;

        SetElementValue(obj, index, value);
    }

    /// <summary>
    /// Defines a field on an object: obj value -> obj
    /// </summary>
    /// <param name="propertyName">The property name.</param>
    public void DefineField(string propertyName)
    {
        if (_stackPointer < 2)
        {
            ThrowStackUnderflow();
            return;
        }

        var value = Pop();
        var obj = Peek();

        SetPropertyValue(obj, propertyName, value);
    }

    /// <summary>
    /// Gets a property value from an object.
    /// </summary>
    private JSValue GetPropertyValue(JSValue obj, string propertyName)
    {
        // Handle null/undefined
        if (obj.IsNull || obj.IsUndefined)
        {
            _context.ThrowTypeError($"Cannot read property '{propertyName}' of {(obj.IsNull ? "null" : "undefined")}");
            return JSValue.Undefined;
        }

        // Object property access
        if (obj.IsObject)
        {
            var jsObj = obj.AsObject();
            if (jsObj != null)
            {
                return jsObj.Get(propertyName);
            }
        }

        // String length property
        if (obj.IsString && propertyName == "length")
        {
            if (obj.TryGetString(out string? str))
            {
                return JSValue.FromInt32(str.Length);
            }
            return JSValue.FromInt32(0);
        }

        // String index access
        if (obj.IsString && uint.TryParse(propertyName, out uint strIndex))
        {
            if (obj.TryGetString(out string? str) && strIndex < str.Length)
            {
                return JSValue.FromString(str[(int)strIndex].ToString());
            }
            return JSValue.Undefined;
        }

        // TODO: Primitive wrapper objects for number, boolean, etc.
        return JSValue.Undefined;
    }

    /// <summary>
    /// Sets a property value on an object.
    /// </summary>
    private void SetPropertyValue(JSValue obj, string propertyName, JSValue value)
    {
        // Handle null/undefined
        if (obj.IsNull || obj.IsUndefined)
        {
            _context.ThrowTypeError($"Cannot set property '{propertyName}' of {(obj.IsNull ? "null" : "undefined")}");
            return;
        }

        // Object property access
        if (obj.IsObject)
        {
            var jsObj = obj.AsObject();
            if (jsObj != null)
            {
                jsObj.Set(propertyName, value);
            }
        }

        // Primitives - silently ignore (or throw in strict mode)
        // TODO: Handle strict mode
    }

    /// <summary>
    /// Gets an element by index from an object or array.
    /// </summary>
    private JSValue GetElementValue(JSValue obj, JSValue index)
    {
        // Handle null/undefined
        if (obj.IsNull || obj.IsUndefined)
        {
            _context.ThrowTypeError($"Cannot read property of {(obj.IsNull ? "null" : "undefined")}");
            return JSValue.Undefined;
        }

        // Fast path: integer index on object
        if (index.IsInt && obj.IsObject)
        {
            var jsObj = obj.AsObject();
            if (jsObj != null)
            {
                int intIndex = index.ToInt32();
                if (intIndex >= 0)
                {
                    return jsObj.Get((uint)intIndex);
                }
                // Negative index - convert to string key
                return jsObj.Get(intIndex.ToString());
            }
        }

        // Fast path: integer index on string
        if (index.IsInt && obj.IsString)
        {
            int intIndex = index.ToInt32();
            if (obj.TryGetString(out string? str) && intIndex >= 0 && intIndex < str.Length)
            {
                return JSValue.FromString(str[intIndex].ToString());
            }
            return JSValue.Undefined;
        }

        // Convert index to property key
        string propertyKey = JSValueConversion.ToString(index);

        // Try as numeric index first
        if (uint.TryParse(propertyKey, out uint uintIndex))
        {
            if (obj.IsObject)
            {
                var jsObj = obj.AsObject();
                if (jsObj != null)
                {
                    return jsObj.Get(uintIndex);
                }
            }
            if (obj.IsString)
            {
                if (obj.TryGetString(out string? str) && uintIndex < str.Length)
                {
                    return JSValue.FromString(str[(int)uintIndex].ToString());
                }
                return JSValue.Undefined;
            }
        }

        // String property access
        return GetPropertyValue(obj, propertyKey);
    }

    /// <summary>
    /// Sets an element by index on an object or array.
    /// </summary>
    private void SetElementValue(JSValue obj, JSValue index, JSValue value)
    {
        // Handle null/undefined
        if (obj.IsNull || obj.IsUndefined)
        {
            _context.ThrowTypeError($"Cannot set property of {(obj.IsNull ? "null" : "undefined")}");
            return;
        }

        // Fast path: integer index on object
        if (index.IsInt && obj.IsObject)
        {
            var jsObj = obj.AsObject();
            if (jsObj != null)
            {
                int intIndex = index.ToInt32();
                if (intIndex >= 0)
                {
                    jsObj.Set((uint)intIndex, value);
                    return;
                }
                // Negative index - convert to string key
                jsObj.Set(intIndex.ToString(), value);
                return;
            }
        }

        // Convert index to property key
        string propertyKey = JSValueConversion.ToString(index);

        // Try as numeric index first
        if (uint.TryParse(propertyKey, out uint uintIndex) && obj.IsObject)
        {
            var jsObj = obj.AsObject();
            if (jsObj != null)
            {
                jsObj.Set(uintIndex, value);
                return;
            }
        }

        // String property access
        SetPropertyValue(obj, propertyKey, value);
    }

    #endregion

    #region Push Operations

    /// <summary>
    /// Pushes undefined onto the stack.
    /// </summary>
    public void PushUndefined()
    {
        Push(JSValue.Undefined);
    }

    /// <summary>
    /// Pushes null onto the stack.
    /// </summary>
    public void PushNull()
    {
        Push(JSValue.Null);
    }

    /// <summary>
    /// Pushes true onto the stack.
    /// </summary>
    public void PushTrue()
    {
        Push(JSValue.True);
    }

    /// <summary>
    /// Pushes false onto the stack.
    /// </summary>
    public void PushFalse()
    {
        Push(JSValue.False);
    }

    /// <summary>
    /// Pushes a 32-bit integer onto the stack.
    /// </summary>
    /// <param name="value">The integer value to push.</param>
    public void PushI32(int value)
    {
        Push(JSValue.FromInt32(value));
    }

    /// <summary>
    /// Pushes a double onto the stack.
    /// </summary>
    /// <param name="value">The double value to push.</param>
    public void PushDouble(double value)
    {
        Push(JSValue.FromDouble(value));
    }

    /// <summary>
    /// Pushes a string onto the stack.
    /// </summary>
    /// <param name="value">The string value to push.</param>
    public void PushString(string value)
    {
        Push(JSValue.FromString(value));
    }

    #endregion

    #region Type Conversion Helpers

    /// <summary>
    /// Converts a value to its primitive representation.
    /// </summary>
    /// <param name="value">The value to convert.</param>
    /// <param name="preferredType">The preferred type hint ("string" or "number").</param>
    /// <returns>The primitive value.</returns>
    private JSValue ToPrimitive(JSValue value, string? preferredType = null)
    {
        if (!value.IsObject)
            return value;

        // TODO: Implement proper ToPrimitive with valueOf/toString calls
        // For now, just convert to string for objects
        return JSValue.FromString(value.ToString() ?? "[object Object]");
    }

    #endregion

    #region Bytecode Execution

    /// <summary>
    /// Executes a single opcode.
    /// </summary>
    /// <param name="opcode">The opcode to execute.</param>
    /// <returns>True if execution should continue, false if complete or exception.</returns>
    public bool ExecuteOpCode(OpCode opcode)
    {
        switch (opcode)
        {
            // Push values
            case OpCode.Undefined:
                PushUndefined();
                return true;
            case OpCode.Null:
                PushNull();
                return true;
            case OpCode.PushTrue:
                PushTrue();
                return true;
            case OpCode.PushThis:
                if (_currentFrame != null)
                    Push(_currentFrame.ThisValue);
                else
                    Push(JSValue.Undefined);
                return true;
            case OpCode.PushFalse:
                PushFalse();
                return true;

            // Stack operations
            case OpCode.Drop:
                Drop();
                return true;
            case OpCode.Dup:
                Dup();
                return true;
            case OpCode.Dup2:
                Dup2();
                return true;
            case OpCode.Dup3:
                Dup3();
                return true;
            case OpCode.Dup1:
                Dup1();
                return true;
            case OpCode.Nip:
                Nip();
                return true;
            case OpCode.Nip1:
                Nip1();
                return true;
            case OpCode.Swap:
                Swap();
                return true;
            case OpCode.Rot3L:
                Rot3L();
                return true;
            case OpCode.Rot3R:
                Rot3R();
                return true;
            case OpCode.Perm3:
                Perm3();
                return true;
            case OpCode.Insert2:
                Insert2();
                return true;
            case OpCode.Insert3:
                Insert3();
                return true;

            // Arithmetic
            case OpCode.Add:
                Add();
                return true;
            case OpCode.Sub:
                Sub();
                return true;
            case OpCode.Mul:
                Mul();
                return true;
            case OpCode.Div:
                Div();
                return true;
            case OpCode.Mod:
                Mod();
                return true;
            case OpCode.Pow:
                Pow();
                return true;
            case OpCode.Plus:
                Plus();
                return true;
            case OpCode.Neg:
                Neg();
                return true;
            case OpCode.Inc:
                Inc();
                return true;
            case OpCode.Dec:
                Dec();
                return true;

            // Bitwise
            case OpCode.Not:
                Not();
                return true;
            case OpCode.And:
                And();
                return true;
            case OpCode.Or:
                Or();
                return true;
            case OpCode.Xor:
                Xor();
                return true;
            case OpCode.Shl:
                Shl();
                return true;
            case OpCode.Sar:
                Sar();
                return true;
            case OpCode.Shr:
                Shr();
                return true;

            // Comparison
            case OpCode.Lt:
                Lt();
                return true;
            case OpCode.Lte:
                Lte();
                return true;
            case OpCode.Gt:
                Gt();
                return true;
            case OpCode.Gte:
                Gte();
                return true;
            case OpCode.Eq:
                Eq();
                return true;
            case OpCode.Neq:
                Neq();
                return true;
            case OpCode.StrictEq:
                StrictEq();
                return true;
            case OpCode.StrictNeq:
                StrictNeq();
                return true;

            // Logical
            case OpCode.LNot:
                LogicalNot();
                return true;
            case OpCode.IsUndefinedOrNull:
                IsUndefinedOrNull();
                return true;

            // Array element access (no operands)
            case OpCode.GetArrayEl:
                GetArrayEl();
                return true;
            case OpCode.GetArrayEl2:
                GetArrayEl2();
                return true;
            case OpCode.PutArrayEl:
                PutArrayEl();
                return true;

                // Control flow (short forms handled in Execute loop)
                case OpCode.IfFalse:
                case OpCode.IfTrue:
                case OpCode.Goto:
                case OpCode.IfFalse8:
                case OpCode.IfTrue8:
                case OpCode.Goto8:
                case OpCode.Goto16:
                    // These are handled in Execute where the PC is available
                    _context.ThrowTypeError($"Unexpected control flow opcode in ExecuteOpCode: {opcode}");
                    return false;

            default:
                // Unhandled opcode
                _context.ThrowTypeError($"Unhandled opcode: {opcode}");
                return false;
        }
    }

    /// <summary>
    /// Executes bytecode from a function definition.
    /// </summary>
    /// <param name="function">The function to execute.</param>
    /// <returns>The result of execution.</returns>
    public JSValue Execute(JSFunctionDef function)
    {
        if (function == null)
            throw new ArgumentNullException(nameof(function));

        var bytecode = function.ByteCode.ToArray();
        int pc = 0;

        JSValue returnValue = JSValue.Undefined;
        bool didReturn = false;

        while (pc < bytecode.Length && !HasException && !didReturn)
        {
            var opcode = (OpCode)bytecode[pc++];

            switch (opcode)
            {
                case OpCode.PushConst:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int constIdx = bytecode[pc] |
                                       (bytecode[pc + 1] << 8) |
                                       (bytecode[pc + 2] << 16) |
                                       (bytecode[pc + 3] << 24);
                        pc += 4;
                        if (constIdx < 0 || constIdx >= function.Constants.Count)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Invalid constant index");
                            return JSValue.Exception;
                        }
                        Push(function.Constants.Get(constIdx));
                    }
                    break;

                case OpCode.PushI32:
                    if (pc + 4 > bytecode.Length)
                    {
                        _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                        return JSValue.Exception;
                    }
                    int i32 = bytecode[pc] |
                             (bytecode[pc + 1] << 8) |
                             (bytecode[pc + 2] << 16) |
                             (bytecode[pc + 3] << 24);
                    pc += 4;
                    PushI32(i32);
                    break;

                // Local variable access (u16 index)
                case OpCode.GetLoc:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        GetLoc(idx);
                    }
                    break;

                // Function calls
                case OpCode.Call:
                case OpCode.TailCall:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        ushort argc = (ushort)(bytecode[pc] | (bytecode[pc + 1] << 8));
                        pc += 2;
                        if (_stackPointer < argc + 1)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Stack underflow during call");
                            return JSValue.Exception;
                        }
                        int calleeIndex = _stackPointer - argc - 1;
                        var callee = _stack[calleeIndex];
                        var args = new JSValue[argc];
                        Array.Copy(_stack, _stackPointer - argc, args, 0, argc);

                        var result = CallFunction(callee, JSValue.Undefined, args);
                        if (result.IsException)
                            return JSValue.Exception;

                        // Pop callee and args
                        _stackPointer -= argc + 1;
                        // Push result
                        Push(result);
                    }
                    break;

                case OpCode.CallMethod:
                case OpCode.TailCallMethod:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        ushort argc = (ushort)(bytecode[pc] | (bytecode[pc + 1] << 8));
                        pc += 2;
                        if (_stackPointer < argc + 2)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Stack underflow during method call");
                            return JSValue.Exception;
                        }
                        int thisIndex = _stackPointer - argc - 2;
                        int calleeIndex = _stackPointer - argc - 1;
                        var thisVal = _stack[thisIndex];
                        var callee = _stack[calleeIndex];
                        var args = new JSValue[argc];
                        Array.Copy(_stack, _stackPointer - argc, args, 0, argc);

                        var result = CallFunction(callee, thisVal, args);
                        if (result.IsException)
                            return JSValue.Exception;

                        _stackPointer -= argc + 2;
                        Push(result);
                    }
                    break;

                case OpCode.CallConstructor:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        ushort argc = (ushort)(bytecode[pc] | (bytecode[pc + 1] << 8));
                        pc += 2;
                        if (_stackPointer < argc + 2)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Stack underflow during constructor call");
                            return JSValue.Exception;
                        }
                        int funcIndex = _stackPointer - argc - 2;
                        int newTargetIndex = _stackPointer - argc - 1;
                        var funcVal = _stack[funcIndex];
                        var newTarget = _stack[newTargetIndex];
                        var args = new JSValue[argc];
                        Array.Copy(_stack, _stackPointer - argc, args, 0, argc);

                        // Allocate a simple object with prototype from function if available
                        JSValue thisVal = JSValue.FromObject(new JSObject());
                        if (funcVal.IsObject && funcVal.AsObject() is JSFunction f && f.Prototype is JSObject proto)
                        {
                            thisVal = JSValue.FromObject(new JSObject(proto));
                        }

                        var result = CallFunction(funcVal, thisVal, args, isConstructor: true);
                        if (result.IsException)
                            return JSValue.Exception;

                        _stackPointer -= argc + 2;
                        Push(result);
                    }
                    break;

                // Small fixed-arity calls: func arg0...argN
                case OpCode.Call0:
                case OpCode.Call1:
                case OpCode.Call2:
                case OpCode.Call3:
                    {
                        int argc = opcode switch
                        {
                            OpCode.Call0 => 0,
                            OpCode.Call1 => 1,
                            OpCode.Call2 => 2,
                            OpCode.Call3 => 3,
                            _ => 0
                        };
                        if (_stackPointer < argc + 1)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Stack underflow during callN");
                            return JSValue.Exception;
                        }
                        int calleeIndex = _stackPointer - argc - 1;
                        var callee = _stack[calleeIndex];
                        var args = new JSValue[argc];
                        if (argc > 0)
                        {
                            Array.Copy(_stack, _stackPointer - argc, args, 0, argc);
                        }

                        var result = CallFunction(callee, JSValue.Undefined, args);
                        if (result.IsException)
                            return JSValue.Exception;

                        _stackPointer -= argc + 1;
                        Push(result);
                    }
                    break;

                case OpCode.PutLoc:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        PutLoc(idx);
                    }
                    break;

                case OpCode.SetLoc:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        SetLoc(idx);
                    }
                    break;

                // Argument access (u16 index)
                case OpCode.GetArg:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        GetArg(idx);
                    }
                    break;

                case OpCode.PutArg:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        PutArg(idx);
                    }
                    break;

                case OpCode.SetArg:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        SetArg(idx);
                    }
                    break;

                // Var ref access (u16 index)
                case OpCode.GetVarRef:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        GetVarRef(idx);
                    }
                    break;

                case OpCode.PutVarRef:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        PutVarRef(idx);
                    }
                    break;

                case OpCode.SetVarRef:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        SetVarRef(idx);
                    }
                    break;

                // TDZ-checked access
                case OpCode.GetLocCheck:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        GetLocCheck(idx);
                    }
                    break;

                case OpCode.PutLocCheck:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        PutLocCheck(idx);
                    }
                    break;

                case OpCode.PutLocCheckInit:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        PutLocCheckInit(idx);
                    }
                    break;

                case OpCode.GetVarRefCheck:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        GetVarRefCheck(idx);
                    }
                    break;

                case OpCode.PutVarRefCheck:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        PutVarRefCheck(idx);
                    }
                    break;

                case OpCode.SetLocUninitialized:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc] | (bytecode[pc + 1] << 8);
                        pc += 2;
                        SetLocUninitialized(idx);
                    }
                    break;

                // Property access (u32 atom)
                case OpCode.GetField:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        uint atom = (uint)(bytecode[pc] |
                                          (bytecode[pc + 1] << 8) |
                                          (bytecode[pc + 2] << 16) |
                                          (bytecode[pc + 3] << 24));
                        pc += 4;
                        string propName = _context.Runtime.AtomTable.GetString(new JSAtom(atom));
                        GetField(propName);
                    }
                    break;

                case OpCode.GetField2:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        uint atom = (uint)(bytecode[pc] |
                                          (bytecode[pc + 1] << 8) |
                                          (bytecode[pc + 2] << 16) |
                                          (bytecode[pc + 3] << 24));
                        pc += 4;
                        string propName = _context.Runtime.AtomTable.GetString(new JSAtom(atom));
                        GetField2(propName);
                    }
                    break;

                case OpCode.PutField:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        uint atom = (uint)(bytecode[pc] |
                                          (bytecode[pc + 1] << 8) |
                                          (bytecode[pc + 2] << 16) |
                                          (bytecode[pc + 3] << 24));
                        pc += 4;
                        string propName = _context.Runtime.AtomTable.GetString(new JSAtom(atom));
                        PutField(propName);
                    }
                    break;

                case OpCode.DefineField:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        uint atom = (uint)(bytecode[pc] |
                                          (bytecode[pc + 1] << 8) |
                                          (bytecode[pc + 2] << 16) |
                                          (bytecode[pc + 3] << 24));
                        pc += 4;
                        string propName = _context.Runtime.AtomTable.GetString(new JSAtom(atom));
                        DefineField(propName);
                    }
                    break;

                // Short opcodes for common local indices
                case OpCode.GetLoc0:
                    GetLoc(0);
                    break;
                case OpCode.GetLoc1:
                    GetLoc(1);
                    break;
                case OpCode.GetLoc2:
                    GetLoc(2);
                    break;
                case OpCode.GetLoc3:
                    GetLoc(3);
                    break;
                case OpCode.PutLoc0:
                    PutLoc(0);
                    break;
                case OpCode.PutLoc1:
                    PutLoc(1);
                    break;
                case OpCode.PutLoc2:
                    PutLoc(2);
                    break;
                case OpCode.PutLoc3:
                    PutLoc(3);
                    break;
                case OpCode.SetLoc0:
                    SetLoc(0);
                    break;
                case OpCode.SetLoc1:
                    SetLoc(1);
                    break;
                case OpCode.SetLoc2:
                    SetLoc(2);
                    break;
                case OpCode.SetLoc3:
                    SetLoc(3);
                    break;

                // Short opcodes for common arg indices
                case OpCode.GetArg0:
                    GetArg(0);
                    break;
                case OpCode.GetArg1:
                    GetArg(1);
                    break;
                case OpCode.GetArg2:
                    GetArg(2);
                    break;
                case OpCode.GetArg3:
                    GetArg(3);
                    break;
                case OpCode.PutArg0:
                    PutArg(0);
                    break;
                case OpCode.PutArg1:
                    PutArg(1);
                    break;
                case OpCode.PutArg2:
                    PutArg(2);
                    break;
                case OpCode.PutArg3:
                    PutArg(3);
                    break;
                case OpCode.SetArg0:
                    SetArg(0);
                    break;
                case OpCode.SetArg1:
                    SetArg(1);
                    break;
                case OpCode.SetArg2:
                    SetArg(2);
                    break;
                case OpCode.SetArg3:
                    SetArg(3);
                    break;

                // Short opcodes for common var ref indices
                case OpCode.GetVarRef0:
                    GetVarRef(0);
                    break;
                case OpCode.GetVarRef1:
                    GetVarRef(1);
                    break;
                case OpCode.GetVarRef2:
                    GetVarRef(2);
                    break;
                case OpCode.GetVarRef3:
                    GetVarRef(3);
                    break;
                case OpCode.PutVarRef0:
                    PutVarRef(0);
                    break;
                case OpCode.PutVarRef1:
                    PutVarRef(1);
                    break;
                case OpCode.PutVarRef2:
                    PutVarRef(2);
                    break;
                case OpCode.PutVarRef3:
                    PutVarRef(3);
                    break;
                case OpCode.SetVarRef0:
                    SetVarRef(0);
                    break;
                case OpCode.SetVarRef1:
                    SetVarRef(1);
                    break;
                case OpCode.SetVarRef2:
                    SetVarRef(2);
                    break;
                case OpCode.SetVarRef3:
                    SetVarRef(3);
                    break;

                // u8 short opcodes
                case OpCode.GetLoc8:
                    {
                        if (pc >= bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc++];
                        GetLoc(idx);
                    }
                    break;
                case OpCode.PutLoc8:
                    {
                        if (pc >= bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc++];
                        PutLoc(idx);
                    }
                    break;
                case OpCode.SetLoc8:
                    {
                        if (pc >= bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int idx = bytecode[pc++];
                        SetLoc(idx);
                    }
                    break;

                // Control flow: conditional and unconditional jumps (32-bit offsets)
                case OpCode.IfFalse:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int offset = bytecode[pc] |
                                    (bytecode[pc + 1] << 8) |
                                    (bytecode[pc + 2] << 16) |
                                    (bytecode[pc + 3] << 24);
                        pc += 4;
                        var cond = Pop();
                        if (!JSValueConversion.ToBoolean(cond))
                        {
                            pc += offset;
                        }
                    }
                    break;

                case OpCode.IfTrue:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int offset = bytecode[pc] |
                                    (bytecode[pc + 1] << 8) |
                                    (bytecode[pc + 2] << 16) |
                                    (bytecode[pc + 3] << 24);
                        pc += 4;
                        var cond = Pop();
                        if (JSValueConversion.ToBoolean(cond))
                        {
                            pc += offset;
                        }
                    }
                    break;

                case OpCode.Goto:
                    {
                        if (pc + 4 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        int offset = bytecode[pc] |
                                    (bytecode[pc + 1] << 8) |
                                    (bytecode[pc + 2] << 16) |
                                    (bytecode[pc + 3] << 24);
                        pc += 4;
                        pc += offset;
                    }
                    break;

                // Control flow: short jumps (8-bit signed offsets)
                case OpCode.IfFalse8:
                    {
                        if (pc >= bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        sbyte offset = unchecked((sbyte)bytecode[pc++]);
                        var cond = Pop();
                        if (!JSValueConversion.ToBoolean(cond))
                        {
                            pc += offset;
                        }
                    }
                    break;

                case OpCode.IfTrue8:
                    {
                        if (pc >= bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        sbyte offset = unchecked((sbyte)bytecode[pc++]);
                        var cond = Pop();
                        if (JSValueConversion.ToBoolean(cond))
                        {
                            pc += offset;
                        }
                    }
                    break;

                case OpCode.Goto8:
                    {
                        if (pc >= bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        sbyte offset = unchecked((sbyte)bytecode[pc++]);
                        pc += offset;
                    }
                    break;

                // Control flow: 16-bit signed offset jump
                case OpCode.Goto16:
                    {
                        if (pc + 2 > bytecode.Length)
                        {
                            _context.ThrowError(JSErrorType.RangeError, "Bytecode overrun");
                            return JSValue.Exception;
                        }
                        short offset = (short)(bytecode[pc] | (bytecode[pc + 1] << 8));
                        pc += 2;
                        pc += offset;
                    }
                    break;

                // Function returns
                case OpCode.Return:
                    returnValue = Pop();
                    didReturn = true;
                    break;
                case OpCode.ReturnUndef:
                    returnValue = JSValue.Undefined;
                    didReturn = true;
                    break;

                default:
                    if (!ExecuteOpCode(opcode))
                        return JSValue.Exception;
                    break;
            }
        }

        return didReturn ? returnValue : (_stackPointer > 0 ? Pop() : JSValue.Undefined);
    }

    #endregion

    #region Exception Helpers

    private void ThrowStackOverflow()
    {
        _context.ThrowError(JSErrorType.RangeError, "Stack overflow");
    }

    private void ThrowStackUnderflow()
    {
        _context.ThrowError(JSErrorType.RangeError, "Stack underflow");
    }

    #endregion
}
